<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBanHang" Class="dbBanHangDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=serverg8-01;Initial Catalog=QuanLyBanHang;User ID=sa" SettingsObjectName="QuanLyBanHang.Properties.Settings" SettingsPropertyName="QuanLyBanHangConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChamCong" Member="ChamCongs">
    <Type Name="ChamCong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Chot" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ChamCong_ChamCong_ChiTiet" Member="ChamCong_ChiTiets" ThisKey="ID" OtherKey="ID" Type="ChamCong_ChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="MaU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GiamDoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoGiamDoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TruongPhong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoPhong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChamCong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="An" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Hinh" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_ChamCong_ChiTiet" Member="ChamCong_ChiTiets" ThisKey="MaU" OtherKey="MaU" Type="ChamCong_ChiTiet" />
      <Association Name="User_PhanQuyenNguoiDung" Member="PhanQuyenNguoiDungs" ThisKey="MaU" OtherKey="MaU" Type="PhanQuyenNguoiDung" />
      <Association Name="PhongBan_User" Member="PhongBan" ThisKey="IDPhong" OtherKey="ID" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChamCong_ChiTiet" Member="ChamCong_ChiTiets">
    <Type Name="ChamCong_ChiTiet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N2" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N3" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N4" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N5" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N6" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N7" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N8" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N9" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N10" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N11" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N12" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N13" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N14" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N15" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N16" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N17" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N18" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N19" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N20" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N21" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N22" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N23" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N24" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N25" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N26" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N27" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N28" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N29" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N30" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N31" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LuongCoBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuongKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TamUng1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TamUng2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TamUng3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BoiDuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuongDotXuat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuongLe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuongThang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuongQuy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuongNam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhuCapXang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhuCapDienThoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienCom1Ngay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuongThucLanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ChamCong_ChamCong_ChiTiet" Member="ChamCong" ThisKey="ID" OtherKey="ID" Type="ChamCong" IsForeignKey="true" />
      <Association Name="User_ChamCong_ChiTiet" Member="User" ThisKey="MaU" OtherKey="MaU" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MST" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiNhanHang" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoaiNhanHang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenMenu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMenuCha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenuCha" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_PhanQuyenNguoiDung" Member="PhanQuyenNguoiDungs" ThisKey="MaMenu" OtherKey="MaMenu" Type="PhanQuyenNguoiDung" />
      <Association Name="Menu_PhanQuyenNhom" Member="PhanQuyenNhoms" ThisKey="MaMenu" OtherKey="MaMenu" Type="PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.Nhom" Member="Nhoms">
    <Type Name="Nhom">
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Nhom_PhanQuyenNhom" Member="PhanQuyenNhoms" ThisKey="MaNhom" OtherKey="MaNhom" Type="PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyenNguoiDung" Member="PhanQuyenNguoiDungs">
    <Type Name="PhanQuyenNguoiDung">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuanLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_PhanQuyenNguoiDung" Member="Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="Menu" IsForeignKey="true" />
      <Association Name="User_PhanQuyenNguoiDung" Member="User" ThisKey="MaU" OtherKey="MaU" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyenNhom" Member="PhanQuyenNhoms">
    <Type Name="PhanQuyenNhom">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuanLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_PhanQuyenNhom" Member="Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="Menu" IsForeignKey="true" />
      <Association Name="Nhom_PhanQuyenNhom" Member="Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="Nhom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PhongBan_User" Member="Users" ThisKey="ID" OtherKey="IDPhong" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HangSanXuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Hinh" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SanPham_SanPham_Nhom_ChiTiet" Member="SanPham_Nhom_ChiTiets" ThisKey="ID" OtherKey="IDSanPham" Type="SanPham_Nhom_ChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham_Nhom" Member="SanPham_Nhoms">
    <Type Name="SanPham_Nhom">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="An" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SanPham_Nhom_SanPham_Nhom_ChiTiet" Member="SanPham_Nhom_ChiTiets" ThisKey="ID" OtherKey="IDSanPham_Nhom" Type="SanPham_Nhom_ChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham_Nhom_ChiTiet" Member="SanPham_Nhom_ChiTiets">
    <Type Name="SanPham_Nhom_ChiTiet">
      <Column Name="IDSanPham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDSanPham_Nhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SanPham_SanPham_Nhom_ChiTiet" Member="SanPham" ThisKey="IDSanPham" OtherKey="ID" Type="SanPham" IsForeignKey="true" />
      <Association Name="SanPham_Nhom_SanPham_Nhom_ChiTiet" Member="SanPham_Nhom" ThisKey="IDSanPham_Nhom" OtherKey="ID" Type="SanPham_Nhom" IsForeignKey="true" />
    </Type>
  </Table>
</Database>